# Pre-commit configuration for eval-hub
repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: (\.ipynb$|^docs/.*\.(html|json)$)
      - id: end-of-file-fixer
        exclude: (\.ipynb$|^docs/.*\.(html|json)$)
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
        exclude: (\.ipynb$|^\.vscode/)
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements
      # prevent committing to main branch for admins
      - id: no-commit-to-branch
        args: [--branch, main]
        stages: [pre-push]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Local checks
  - repo: local
    hooks:
      - id: go-test
        name: go unit and integration tests
        entry: make
        args: [test, test-fvt]
        language: system
        types: [go]
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: RuboCop
      - id: shellcheck
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.2
    hooks:
      - id: pylint
